import { ProductData, ProjectData, ServiceData, ArticleData, TestimonialData } from '../../types/public.js';

export const initialProducts: ProductData[] = [
  {
    id: 'prod-1',
    slug: 'mesin-es-tube-10-ton',
    name: 'Mesin Es Tube 10 Ton / 24 Jam',
    categoryId: 'cat-1',
    tagline: 'Kapasitas menengah ideal untuk pabrik es kristal distribusi kemasan kota.',
    description: 'Evaporator baja stainless SS304 dengan pemotong rotary knife presisi tinggi. Dilengkapi kompresor Bitzer semi-hermetic Jerman dan kondensor pendingin air (water-cooled) yang tahan air asin.',
    capacityTons: 10,
    powerKw: 37.5,
    refrigerant: 'R404A Eco',
    compressorBrand: 'Bitzer Semi-Hermetic (Germany)',
    dimensions: '2.4m x 1.6m x 2.2m',
    isFeatured: true,
    isActive: true,
    sortOrder: 1,
    images: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800'],
    faqs: [
      { question: 'Berapa waktu panen es per siklus?', answer: 'Panen otomatis berlangsung setiap 20 hingga 25 menit.' },
      { question: 'Apakah air pembuat es kontak dengan oli?', answer: 'Tidak sama sekali, sistem tertutup menggunakan food-grade stainless steel SS304.' },
    ],
  },
  {
    id: 'prod-2',
    slug: 'mesin-es-block-direct-cooling-20-ton',
    name: 'Mesin Es Block Direct Cooling 20 Ton',
    categoryId: 'cat-3',
    tagline: 'Es balok padat tanpa air garam (brine water), ramah lingkungan.',
    description: 'Sistem cetak es balok aluminium alloy dengan pendinginan freon langsung. Panen cepat hanya dalam 4-6 jam menggunakan hot gas defrosting tanpa garam.',
    capacityTons: 20,
    powerKw: 75,
    refrigerant: 'R404A',
    compressorBrand: 'Hanbell Screw Compressor',
    dimensions: '6.2m x 2.1m x 2.4m',
    isFeatured: true,
    isActive: true,
    sortOrder: 2,
    images: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800'],
  },
  {
    id: 'prod-3',
    slug: 'mesin-es-flake-5-ton-laut',
    name: 'Mesin Es Flake Marine 5 Ton / 24 Jam',
    categoryId: 'cat-4',
    tagline: 'Es serpihan kering suhu -7°C dirancang khusus tahan korosi air laut.',
    description: 'Drum evaporator stainless steel SS316 dengan pisau pemotong spiral. Sangat cocok dipasang langsung di atas dek kapal tangkap tuna atau di Tempat Pelelangan Ikan (TPI).',
    capacityTons: 5,
    powerKw: 22,
    refrigerant: 'R404A',
    compressorBrand: 'Bitzer Scroll / Piston',
    dimensions: '1.8m x 1.4m x 1.7m',
    isFeatured: true,
    isActive: true,
    sortOrder: 3,
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800'],
  },
];

export const initialProjects: ProjectData[] = [
  {
    id: 'proj-1',
    slug: 'pabrik-es-tube-sidoarjo',
    title: 'Pabrik Es Tube Komersial 30 Ton di Sentra Pergudangan Sidoarjo',
    clientName: 'PT Samudra Es Makmur',
    location: 'Sidoarjo, Jawa Timur',
    capacity: '30 Ton / Hari',
    summary: 'Penyediaan 3 unit mesin es tube 10 Ton terintegrasi dengan conveyor otomatis dan cold room penampung es kapasitas 50 Ton.',
    description: 'Instalasi turnkey lengkap mencakup sistem purifikasi air reverse osmosis (RO), cooling tower tertutup, dan panel otomatis PLC Siemens.',
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800',
    status: 'PUBLISHED',
    isFeatured: true,
    completionDate: '2024-11-15',
    createdAt: '2024-11-15T00:00:00Z',
  },
  {
    id: 'proj-2',
    slug: 'cold-storage-tuna-bitung',
    title: 'Fasilitas Cold Storage & Blast Freezer Ekspor Ikan Tuna Bitung',
    clientName: 'PT Pasifik Bahari Nusantara',
    location: 'Pelabuhan Bitung, Sulawesi Utara',
    capacity: 'Freezer -35°C (100 Ton)',
    summary: 'Pembangunan gudang beku standar ekspor Uni Eropa dengan sistem kompresor Bitzer ganda dan pintu hermetic otomatis.',
    description: 'Proyek mencakup isolasi panel PIR 150mm anti api dan pemantauan suhu digital cloud 24 jam.',
    coverImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    status: 'PUBLISHED',
    isFeatured: true,
    completionDate: '2025-01-20',
    createdAt: '2025-01-20T00:00:00Z',
  },
];

export const initialServices: ServiceData[] = [
  {
    id: 'srv-1',
    slug: 'fabrikasi-mesin-es-kustom',
    title: 'Fabrikasi Mesin Es Kustom',
    tagline: 'Rancang bangun mesin kapasitas 1 hingga 100 Ton per hari',
    description: 'Perakitan mesin es tabung, flake, dan balok direct cooling disesuaikan dengan kondisi daya PLN pelanggan.',
    features: ['Evaporator stainless food-grade SS304/SS316', 'Uji beban kontinu 72 jam di workshop', 'Garansi suku cadang 12 bulan'],
    status: 'PUBLISHED',
    isFeatured: true,
    sortOrder: 1,
  },
  {
    id: 'srv-2',
    slug: 'instalasi-ruang-cold-storage',
    title: 'Rancang Bangun & Instalasi Cold Storage',
    tagline: 'Ruang Chiller, Freezer, dan Blast Freezer Turnkey',
    description: 'Konstruksi gudang pendingin modular berinsulasi tinggi dengan suhu stabil -20°C s/d -40°C.',
    features: ['Panel polyurethane densitas tinggi 42 kg/m³', 'Unit kondensasi Bitzer / Copeland', 'Sertifikasi uji kebocoran termal'],
    status: 'PUBLISHED',
    isFeatured: true,
    sortOrder: 2,
  },
  {
    id: 'srv-3',
    slug: 'servis-berkala-overhaul-kompresor',
    title: 'Pemeliharaan Rutin & Overhaul Kompresor',
    tagline: 'Tim teknisi pendingin siaga 24 jam di seluruh Indonesia',
    description: 'Layanan servis pencegahan, perbaikan darurat kebocoran freon, dan rekondisi kompresor semi-hermetic.',
    features: ['Suku cadang orisinal Bitzer & Danfoss', 'Penggantian oli refrigerant food grade', 'Kunjungan berkala terjadwal'],
    status: 'PUBLISHED',
    isFeatured: true,
    sortOrder: 3,
  },
];

export const initialArticles: ArticleData[] = [
  {
    id: 'art-1',
    slug: 'analisis-keuntungan-bisnis-pabrik-es-kristal-tube',
    title: 'Analisis Keuntungan & Balik Modal Bisnis Pabrik Es Kristal Tube di Indonesia',
    category: 'Bisnis & Investasi',
    excerpt: 'Menghitung biaya pokok produksi per kg, konsumsi daya listrik PLN, margin penjualan, dan simulasi ROI pada mesin kapasitas 10-30 ton.',
    content: 'Kebutuhan es kristal higienis terus meningkat seiring bertumbuhnya gerai kopi, restoran, dan hotel di kota-kota Indonesia. Dengan harga jual rata-rata Rp 12.000 - Rp 15.000 per karung 10kg dan biaya produksi berkisar Rp 3.500 per karung, margin kotor mencapai lebih dari 60%.',
    readTimeMin: 6,
    publishedAt: '2025-02-10T08:00:00Z',
    author: { name: 'Ir. Hendra Kusuma', department: 'Senior Refrigeration Specialist' },
  },
  {
    id: 'art-2',
    slug: 'mengapa-mesin-es-block-direct-cooling-lebih-hemat-listrik',
    title: 'Mengapa Mesin Es Block Direct Cooling Lebih Hemat Listrik Dibanding Kolam Brine',
    category: 'Teknologi Mesin',
    excerpt: 'Perbandingan koefisien kinerja termal refrigerasi langsung melawan media air garam konvensional yang rentan korosi.',
    content: 'Sistem direct cooling meniadakan pompa sirkulasi brine water yang memakan daya 7.5 kW terus-menerus. Selain itu, transfer kalor langsung ke aluminium alloy memangkas waktu pembekuan hingga 50%, menghemat konsumsi energi total hingga 28%.',
    readTimeMin: 5,
    publishedAt: '2025-01-25T08:00:00Z',
    author: { name: 'Bambang Trianto, S.T.', department: 'Workshop Lead Engineer' },
  },
];

export const initialTestimonials: TestimonialData[] = [
  {
    id: 'test-1',
    clientName: 'Ir. Budi Santoso',
    company: 'PT Samudra Jaya Perkasa (Surabaya)',
    role: 'Direktur Operasional',
    content: 'Mesin es tube 20 Ton dari EVERFRESH telah beroperasi lebih dari 3 tahun tanpa kendala berarti. Konsumsi daya listrik stabil dan es yang dihasilkan sangat jernih disukai pelanggan F&B.',
    rating: 5,
    status: 'PUBLISHED',
    isFeatured: true,
  },
  {
    id: 'test-2',
    clientName: 'Ibu Stefanie Wijaya',
    company: 'CV Muara Seafood Ekspor (Jakarta)',
    role: 'Pemilik Usaha',
    content: 'Cold room dan mesin es flake mereka sangat membantu menjaga kesegaran udang ekspor kami di Muara Baru. Teknisi sangat responsif saat jadwal servis berkala.',
    rating: 5,
    status: 'PUBLISHED',
    isFeatured: true,
  },
];
